language: php
services: docker

php:
  - 7.2

before_install:
  - sudo service mysql stop

script:
  # Build the Drupal image.
  - docker build -t geerlingguy/drupal-for-kubernetes .

  # Bring up the environment, wait for MySQL to be reachable.
  - cp tests/docker-compose.yml ./docker-compose.yml
  - docker-compose up -d
  - |
    while ! mysqladmin ping -h127.0.0.1 -u drupal -pdrupal --silent; do
      sleep 1
    done

  # Install Drupal.
  - >
    docker-compose exec drupal bash -c
    'drush site:install minimal
    --db-url="mysql://drupal:$DRUPAL_DATABASE_PASSWORD@$DRUPAL_DATABASE_HOST/drupal"
    --site-name="Drupal Example Site for Kubernetes"
    --existing-config
    -y'

  # Verify Drupal is running.
  - curl --head http://localhost/
