language: php
services: docker

php:
  - 7.2

before_install:
  - sudo service mysql stop

script:
  # Build the Drupal image.
  - docker build -t geerlingguy/drupal-example-kubernetes .

  # Bring up the environment.
  - docker-compose up -d

  # Install Drupal.
  - docker-compose exec drupal bash -c "vendor/bin/drush site-install standard --db-url="mysql://drupal:$DRUPAL_DB_PASSWORD@$DRUPAL_DB_HOST/drupal" --site-name='Drupal Example Site for Kubernetes' -y"

  # Verify Drupal is running.
  - curl --head http://localhost/
