---
version: '3'

services:
  drupal:
    image: geerlingguy/drupal-for-kubernetes:latest
    container_name: drupal-for-kubernetes
    environment:
      DRUPAL_DATABASE_HOST: 'mysql'
      DRUPAL_DATABASE_PORT: '3306'
      DRUPAL_DATABASE_NAME: 'drupal'
      DRUPAL_DATABASE_USERNAME: 'drupal'
      DRUPAL_DATABASE_PASSWORD: 'drupal'
      DRUPAL_HASH_SALT: 'fe918c992fb1bcfa01f32303c8b21f3d0a0'
      DRUPAL_DOWNLOAD_IF_NOT_PRESENT: 'false'
    ports:
      - "80:80"
    restart: on-failure
    # Share the project into the container for local development. Comment out
    # this line to test the production-ready pre-built container codebase.
    volumes: ['./:/var/www/html:rw,delegated']

  mysql:
    image: mariadb:10
    container_name: drupal-mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
